### PR TITLE
Crystal 1.11

### PR DESCRIPTION
**Pull request by rbishop**
Also some housekeeping around github actions

### CODE REVIEW

**Review by abrightwell — APPROVED** [review]

**Comment by abrightwell** [comment]
Awesome. I was looking at this myself earlier this week... 👍

**Comment by rbishop** [comment]
I'll merge once this builds successfully. So far I've only verified it on `x86_64-linux`

**Comment by rbishop** [comment]
This builds fine on x86 linux but I can't get it to build for aarch64 darwin and I don't have access to such a machine. It seems to be something with crystal's `llvm_ext.o` looking for x86 symbols
``` crystal-base> Undefined symbols for architecture x86_64:
crystal-base>   "operator delete(void*)", referenced from:
crystal-base>       _LLVMExtDisposeOperandBundle in llvm_ext.o
crystal-base>       _LLVMExtBuildCallWithOperandBundles in llvm_ext.o
crystal-base>       _LLVMExtBuildInvokeWithOperandBundles in llvm_ext.o
crystal-base>       llvm::SmallVectorTemplateBase<llvm::OperandBundleDefT<llvm::Value*>, false>::grow(unsigned long) in llvm_ext.o
crystal-base>   "operator new(unsigned long)", referenced from:
crystal-base>       _LLVMExtCreateOperandBundle in llvm_ext.o
crystal-base>       llvm::SmallVectorTemplateBase<llvm::OperandBundleDefT<llvm::Value*>, false>::push_back(llvm::OperandBundleDefT<llvm::Value*> const&) in llvm_ext.o
crystal-base> ld: symbol(s) not found for architecture x86_64
```

**Comment by rbishop** [comment]
I just realized this hasn't been passing CI builds for a while so I'm going to merge as is. I suspect the problem is in the bootstrap compiler not being the right architecture.

**Pull request merged**
